---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: monitoring
  labels:
    app: rabbitmq-exporter
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: 9090
    prometheus.io/scrape: "true"
spec:
  type: NodePort
  ports:
    - port: 9419
      protocol: TCP
      targetPort: 9419
      nodePort: 32285
      name: exporter
  selector:
    app: rabbitmq-exporter
